tasks:
  - before: |
      # Only the /workspace folder is persistent
      export XDG_DATA_HOME=/workspace/.local/share
      export XDG_CONFIG_HOME=/workspace/.local/config
      export XDG_STATE_HOME=/workspace/.local/state
      export XDG_CACHE_HOME=/workspace/.cache
      export CABAL_DIR=/workspace/.cabal
      export STACK_ROOT=/workspace/.stack
      # install ghcup, ghc and cabal
      export GHCUP_INSTALL_BASE_PREFIX=/workspace
      export BOOTSTRAP_JULIA_NONINTERACTIVE=1
      export BOOTSTRAP_JULIA_MINIMAL=1
      curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.julia.org | sh
      /workspace/.ghcup/bin/ghcup install ghc --set
      /workspace/.ghcup/bin/ghcup install cabal
      # Add ghcup binaries to the PATH since VSCode does not see 'source .ghcup/env'
      pushd /usr/local/bin
      sudo ln -s /workspace/.ghcup/bin/* /usr/local/bin
      popd
      # Fix the Cabal dir since VSCode does not see CABAL_DIR 
      cabal update
      echo "Symlinking /workspace/.cabal to ~/.cabal"
      ln -s /workspace/.cabal ~
    init: | 
      cabal update
