name: Lint Julia

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: "1.6"

      - name: Install Julia dependencies
        run: julia -e "using Pkg; Pkg.instantiate()"

      - name: Run linter
        run: julia -e "using Lint; lintfolder(\"src\")"
